### PR TITLE
fix(opencode): harden agent swarm auth onboarding

### LINKED ISSUE #41: Agent Swarm auth onboarding can leave dead sessions and unsupported auth dead ends
## Summary

Agent Swarm mode still has a few auth-onboarding failures that break the happy path for local agencies.

## Problems

- Sending the first normal message before auth can leave a new empty session behind and push the UI into a bad state.
- Provider-credential failures are not consistently routed back into `/auth`.
- Agent Swarm auth still exposes unsupported provider/auth choices, which creates dead ends and confusion.
- Browser auth feedback is weak, so it is not clear what happened when sign-in fails.

## Expected

- First message sends should be blocked until supported auth exists.
- Agent Swarm mode should only show supported auth choices for now.
- Provider-credential failures should return the user to `/auth`, while agency-server auth failures should return them to `/connect`.
- The browser-auth path should clearly tell the user what happened and use the default browser.

## Verification target

- Focused TUI auth tests
- Real local Agency Swarm request checks for OpenAI OAuth and Anthropic API key forwarding

### PR DESCRIPTION
**Pull request by nicko-ai**
### Issue for this PR

Closes #41

### Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Refactor / code improvement
- [ ] Documentation

### What does this PR do?

This tightens the Agent Swarm auth path without changing upstream provider support globally.

It blocks the first normal message send until supported auth exists, keeps the Agent Swarm auth UI limited to OpenAI and Anthropic for now, routes provider-credential failures back into `/auth`, routes agency-server auth failures back into `/connect`, and deletes a newly created empty session if the first prompt fails immediately.

It also improves the browser-auth UX in Agent Swarm mode by opening the default browser, showing clearer inline/toast errors, and keeping unsupported upstream provider code untouched.

### How did you verify your code works?

- `bun test test/cli/tui/session-error.test.ts test/cli/tui/provider-auth.test.ts`
- `bun test test/session/agency-swarm.test.ts --test-name-pattern 'stream sends stored OpenAI OAuth auth to a real local agency server|stream sends stored Anthropic API auth to a real local agency server'`
- `bun run typecheck`

### Screenshots / recordings

- Not included yet.

### Checklist

- [x] I have tested my changes locally
- [x] I have not included unrelated changes in this PR

### CODE REVIEW

File: packages/opencode/src/cli/cmd/tui/component/prompt/index.tsx [hunk 1]
```diff
@@ -698,8 +754,8 @@ export function Prompt(props: PromptProps) {
           })),
       })
```
Comment (nicko-ai) [inline packages/opencode/src/cli/cmd/tui/component/prompt/index.tsx:755]: Tracing the composer-not-clearing regression: this is the line that changed upstream fire-and-forget prompt submit into an awaited call. PR #88 later carried this behavior forward, but it did not introduce this exact line; git blame points to this PR/commit. Because `clearSubmittedPrompt(currentMode)` runs after this block, awaiting here keeps the composer text visible until the stream finishes. The fix should restore the upstream fire-and-forget shape and put fork auth-error handling in `.catch()` without blocking prompt clearing.
